server:
  port: 8083

spring:
  profile: default
  application:
    name: chart-service
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
