server:
  port: 8083

spring:
  profile: default
  application:
    name: chart-service

reporting:
  service:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    root: DEBUG
    org.project.chartservice: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
