server:
  port: 8084

spring:
  application:
    name: email-service

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME} # Reads from env var
    password: ${GMAIL_PASSWORD} # Reads from env var
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true # Keep true for dev to see SMTP logs

  # RabbitMQ Configuration (Local defaults)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Resiliency
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.project.emailservice: DEBUG
    org.springframework.mail: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always