spring:
  # Override RabbitMQ host for Docker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Override Eureka URL for Docker
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# Ensure logging is visible in Docker logs
logging:
  level:
    root: INFO
    org.project.emailservice: DEBUG