spring:
  application:
    name: email-service

  config:
    import: "configserver:http://config-server:8888"

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000ms

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kafka:
  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: 8084

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: "http://eureka-server:8761/eureka/"
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,eureka
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      project:
        emailservice: DEBUG
      springframework:
        mail: DEBUG

email:
  providers:
    gmail:
      host: smtp.gmail.com
      port: 587
      username: ${GMAIL_USERNAME:}
      password: ${GMAIL_PASSWORD:}
      enabled: true

rabbitmq:
  exchange:
    name: email.exchange
  queue:
    urgent:
      name: email.queue.urgent
    high:
      name: email.queue.high
    normal:
      name: email.queue.normal
    low:
      name: email.queue.low
    dlq:
      name: email.queue.dlq
    name: email.queue.normal
  routing:
    key:
      urgent: email.urgent
      high: email.high
      normal: email.normal
      low: email.low
      name: email.normal
