spring:
  application:
    name: excel-service

jira:
  service:
     url: http://jira-fetch-service:8081

reporting:
  service:
    url: http://reporting-service:8082

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,eureka
      base-path: /actuator
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.project.excelservice: DEBUG
    org.springframework.cloud.config: DEBUG  # Added
    org.eclipse.jgit: DEBUG  # Added
    org.springframework.cloud.netflix.eureka: DEBUG  # Added