spring:
  application:
    name: jira-fetch-service
  datasource:
    url: jdbc:postgresql://postgres:5432/jira_db
    username: jira
    password: postgres
    driver-class-name: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  cloud:
    config:
      fail-fast: true  
      retry:
        max-attempts: 10
        initial-interval: 5000
        multiplier: 1.5
        max-interval: 15000
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # Use IP in Docker

management:
  endpoints:
    web:
      exposure:
        include: health,info,eureka
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.project.jirafetchservice: DEBUG
    org.springframework.cloud.config: DEBUG  # Added
    org.eclipse.jgit: DEBUG  # Added
    org.springframework.cloud.netflix.eureka: DEBUG  # Added