spring:
  application:
    name: reporting-service
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/reporting_db
    username: reporting
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "configserver:http://localhost:8888"

  data:
    rest:
      base-path: /api

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,eureka
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      project:
        reportingservice: DEBUG
      springframework:
        web:
          reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jira:
  fetch:
    base-url: ${JIRA_FETCH_BASE_URL:http://localhost:8081}

reporting:
  expected-hours-per-month: 160
  performance:
    excellent-threshold: 0.9
    good-threshold: 0.7
    poor-threshold: 0.5
