spring:
  application:
    name: reporting-service
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/reporting_db
    username: reporting
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    redis:
      time-to-live: 600000 
    data:
      redis:
        host: phd-redis
        port: 6379

  data:
    rest:
      base-path: /api

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: reporting-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,eureka
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      project:
        reportingservice: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

reporting:
  expected-hours-per-month: 160
  performance:
    excellent-threshold: 0.9
    good-threshold: 0.7
    poor-threshold: 0.5
