server:
  port: 8082

spring:
  application:
    name: trajet-service

  datasource:
    url: jdbc:postgresql://localhost:5432/trajet_db
    username: trajet
    password: postgres
    driver-class-name: org.postgresql.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  sql:
    init:
      mode: always

  cloud:
    config:
      fail-fast: false  # Enable to surface config issues early
      retry:
        max-attempts: 10
        initial-interval: 5000
        multiplier: 1.5
        max-interval: 15000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.project.trajetservice: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.config: DEBUG  # Added for config debugging
    org.eclipse.jgit: DEBUG  # Added for Git issues
    org.springframework.cloud.netflix.eureka: DEBUG  # For Eureka registration

jwt:
  secret: 0066238a010313091a509d03b52715040a0ed3dc456e0be91c3063e9c6e7cdeb3ed7c5f27e601681072576211f93c5363bfc846db11015264800207c79b587a9
  expiration: 86400000