spring:
  application:
    name: user-service

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,eureka
  endpoint:
    health:
      show-details: always

notification-service:
  url: http://notification-service:8085

jwt:
  secret: dUZOJgciJm1Qq8+O9hx7KXMeeKpbXzQe7hZlFjl2APk=
  expiration: 86400000

logging:
  level:
    org.project.userservice: DEBUG
    org.springframework.cloud.config: DEBUG  # Added
    org.eclipse.jgit: DEBUG  # Added
    org.springframework.cloud.netflix.eureka: DEBUG  # Added