spring:
  application:
    name: user-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,eureka
  endpoint:
    health:
      show-details: always

jwt:
  secret: 0066238a010313091a509d03b52715040a0ed3dc456e0be91c3063e9c6e7cdeb3ed7c5f27e601681072576211f93c5363bfc846db11015264800207c79b587a9
  expiration: 86400000

logging:
  level:
    org.project.userservice: DEBUG
    org.springframework.cloud.config: DEBUG  # Added
    org.eclipse.jgit: DEBUG  # Added
    org.springframework.cloud.netflix.eureka: DEBUG  # Added