spring:
  application:
    name: issue-events
  profiles:
    active: default
  config:
    import: "configserver:http://localhost:8888"

server:
  port: 8087

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - eureka
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.netflix.eureka: DEBUG
