server:
  port: 8081

spring:
  application:
    name: jira-fetch-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jira_db
    username: jira
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.doctorat.inscription: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
